baseurl = "https://gavinstrunk.github.io/"
title = "Gavin Strunk"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Home Page Image
  image = "img/Casual.png"

  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "This is my portfolio website to share research results."
  copyright = "&copy;2022 Gavin Strunk"
  sidebarAbout = [
    "My name is Gavin Strunk, and I am currently a researcher at Scientific Systems in the Intelligent Controls Group. I have worked on a wide variety of projects in fields of control theory, optimization, and artificial intelligence.", 
    "My current research focuses are related to optimal control/MPC, reinforcement learning, and trajectory optimization. This site contains some research from my professional work, but it is primarily meant to share results from my indepedent research projects. Everyone needs a hobby!"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Resume"
  url = "files/Resume.pdf"

  #[[params.navlinks]]
  #name = "CV"
  #url = "files/CV.pdf"

  [params.social]
  email         = "gavin.strunk@gmail.com"
  linkedin      = "https://www.linkedin.com/in/gavinstrunk/"
  github        = "https://github.com/GavinStrunk"
  scholar       = "https://scholar.google.com/citations?user=RasHxcsAAAAJ&hl=en&oi=ao"
