baseURL = "https://gavinstrunk.github.io"
title = "Gavin Strunk Portfolio"
copyright = "Copyright © 2020 Gavin Strunk; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "website-theme"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/categories/Project"
    weight = 0
  [[menu.main]]
    identifier = "Tutorials"
    name = "Tutorials"
    url = "/categories/Tutorial"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  # Settings for the Home page text
  name = "Gavin Strunk"
  description = "Robotics Research Scientist"
  about = """
    This site is a collection of my indepedent research, <br>
    fun projects, and some tutorials. Enjoy!
    """
  homepageImage = "/images/homepage-image.png"

  #Show the social media share a post icons
  share = false
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    email = "gavin.strunk@gmail.com"
    linkedin = "https://www.linkedin.com/in/gavinstrunk/"
    github = "https://github.com/GavinStrunk"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

#[services]
#  [services.instagram]
#    disableInlineCSS = true
#
#  [services.twitter]
#    disableInlineCSS = true
