baseURL = "https://example.com"
title = "Gavin Strunk Portfolio"
copyright = "Copyright © 2020 Gavin Strunk; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
#theme = "hugo-theme-chunky-poster"
theme = "website-theme"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/posts/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
#author = "authors"

[params]
  #author = "Hugo Authors"
  description = "Research Scientist"
  #homepageImage = "/images/homepage-image.jpg"
  homepageImage = "/images/rob2.png"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    email = "gavin.strunk@gmail.com"
    linkedin = "https://linkedin.com"
    github = "https://github.com"
    gitlab = "https://gitlab.com"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

#[services]
#  [services.instagram]
#    disableInlineCSS = true
#
#  [services.twitter]
#    disableInlineCSS = true
