# This workflow builds my Hugo website and deploys it to my user github page

name: CI/CD

#Trigger on master branch
on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # Build on latest Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        persist-credentials: false
        fetch-depth: 0

    # Install dependencies
    # Hugo needs to be a newer version so I am using 0.68.3
    - name: Install Dependencies
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.deb
        sudo dpkg -i hugo*.deb
        rm hugo*.deb

    # You have to set your git credentails so you can push the changes
    - name: Set Git Creds
      run: |
        git config --global user.email "gavin.strunk@gmail.com"
        git config --global user.name "Gavin Strunk"
        
    # Run script to build and deploy the site
    - name: BuildAndDeploy
      run: ./deploy.sh

    # Push the changes
    - name: Push new site
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: public
        repository: GavinStrunk/gavinstrunk.github.io
